# Generated by Django 5.0.7 on 2024-07-27 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomment_productorder_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='user_email',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
        ),
    ]
