# Generated by Django 5.0.7 on 2024-07-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_quantity_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComment',
            new_name='Comment',
        ),
    ]
