# Generated by Django 5.0.7 on 2024-08-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment_is_provide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='name',
        ),
    ]
